name: pomodoro
description: Pomodoro timer.

publish_to: "none"
version: 1.0.0+1

environment:
    sdk: ">=2.12.0 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    flutter_riverpod: ^0.13.1
    bitsdojo_window: ^0.1.5
    audioplayers: ^4.0.1

dev_dependencies:
    flutter_test:
        sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/